---
title: "ATAC"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

library(limma)
library(dplyr)
library(DT)
library(GenomicRanges)
library(tidyr)
library(pheatmap)
library(DESeq2)
library(BSgenome.Mmusculus.UCSC.mm10)
library(tracktables)
library(Rsubread)
library(clusterProfiler)
library(enrichplot)
library(ChIPseeker)
library(org.Mm.eg.db)
library(TxDb.Mmusculus.UCSC.mm10.knownGene)



BiocManager::install("enrichplot")


filePath <- "~/GitHub/hemopoiesis-differentiation/data/Bams/"
sampleNames <- c("ENCFF250YAL", "ENCFF958EPJ", "ENCFF711QAL", "ENCFF620WGW")
peaks <- sapply(sampleNames, function(x) read.csv(file=paste0(filePath, x, "_peaks.narrowpeak"), header=T, sep="\t"), simplify=F)


myPeaks <- lapply(peaks, ChIPQC:::GetGRanges, simple = TRUE)

names(myPeaks) <- c("HSC", "HSC", "CMP", "CMP")

Group=factor(c("HSC","HSC","CMP","CMP"))

myGRangesList<-GRangesList(myPeaks)   

reduced <- reduce(unlist(myGRangesList))
consensusIDs <- paste0("consensus_", seq(1, length(reduced)))
mcols(reduced) <- do.call(cbind, lapply(myGRangesList, function(x) (reduced %over% x) + 0))
reducedConsensus <- reduced
mcols(reducedConsensus) <- cbind(as.data.frame(mcols(reducedConsensus)), consensusIDs)
consensusIDs <- paste0("consensus_", seq(1, length(reducedConsensus)))
reducedConsensus




as.data.frame(elementMetadata(reducedConsensus)) %>% dplyr::select(starts_with("HSC")) %>% 
    vennDiagram(main = "Overlap for Liver open regions")
    
    


myPlot <- as.data.frame(elementMetadata(reducedConsensus)) %>% dplyr::select(-consensusIDs) %>% 
    as.matrix %>% t %>% prcomp %>% .$x %>% data.frame %>% mutate(Samples = rownames(.)) %>% 
    mutate(Group = gsub("_\\d", "", Samples)) %>% ggplot(aes(x = PC1, y = PC2, 
    colour = Group)) + geom_point(size = 5)

myPlot




occurrences <- elementMetadata(reducedConsensus) %>% as.data.frame %>% dplyr::select(-consensusIDs) %>% 
    rowSums

table(occurrences) %>% rev %>% cumsum


consensusToCount <- reducedConsensus[occurrences >= 2, ]

consensusToCount



filePath <- "~/GitHub/hemopoiesis-differentiation/data/Bams/"
sampleNames <- c("ENCFF250YAL", "ENCFF958EPJ", "ENCFF711QAL", "ENCFF620WGW")
bamsToCount<- c("ENCFF250YAL.bam", "ENCFF958EPJ.bam", "ENCFF711QAL.bam", "ENCFF620WGW.bam")

# indexBam(bamsToCount)
regionsToCount <- data.frame(GeneID = paste("ID", seqnames(consensusToCount), 
    start(consensusToCount), end(consensusToCount), sep = "_"), Chr = seqnames(consensusToCount), 
    Start = start(consensusToCount), End = end(consensusToCount), Strand = strand(consensusToCount))
fcResults <- featureCounts(files=bamsToCount,annot.ext=regionsToCount,isPairedEnd = FALSE,countMultiMappingReads = FALSE,maxFragLength=100)


myCounts <- fcResults$counts
colnames(myCounts) <- c("HSC_1","HSC_2","CMP_1","CMP_2")
save(myCounts, file = "countsFromATAC.RData")



pheatmap(myCounts[1:100,], scale='row', show_rownames = FALSE)





metaData <- data.frame(Group, row.names = colnames(myCounts))
atacDDS <- DESeqDataSetFromMatrix(myCounts, metaData, ~Group, rowRanges = consensusToCount)
atacDDS <- DESeq(atacDDS)
atac_Rlog <- rlog(atacDDS)
plotPCA(atac_Rlog, intgroup = "Group", ntop = nrow(atac_Rlog))







HSCMinusCMP<- results(atacDDS, c("Group", "HSC", "CMP"), format = "GRanges")
HSCMinusCMP<- HSCMinusCMP[order(HSCMinusCMP$pvalue)]
HSCMinusCMP



toOverLap <- promoters(TxDb.Mmusculus.UCSC.mm10.knownGene, 500, 500)
HSCMinusCMP <- HSCMinusCMP[(!is.na(HSCMinusCMP$padj) & HSCMinusCMP$pvalue < 0.05) & HSCMinusCMP %over% toOverLap]

makebedtable(HSCMinusCMP, "HSCMinusCMP.html", filePath)




anno_HSCMinusCMP <- annotatePeak(HSCMinusCMP, TxDb = TxDb.Mmusculus.UCSC.mm10.knownGene)


plotAnnoPie(anno_HSCMinusCMP)




head(go1, 10) %>% dplyr::select(ID, Description, pvalue, p.adjust) %>% datatable(elementId = "goEle1")
    
head(go2, 10) %>% dplyr::select(ID, Description, pvalue, p.adjust) %>% datatable(elementId = "goEle2")



ridgeplot(go1)




anno_HSCMinusCMP_GRanges <- as.GRanges(anno_HSCMinusCMP)



anno_HSCMinusCMP_df <- as.data.frame(anno_HSCMinusCMP)
write.table(anno_HSCMinusCMP_df, "anno_HSCMinusCMP.csv", quote = FALSE, row.names = FALSE, sep = ",")












pheatmap(myCounts[1:100,], scale='row', show_rownames = FALSE)





library(stats)
correlationMatrix <- cor(myCounts[1:10000,1:4])


library(corrplot)
corrplot(correlationMatrix, order = 'hclust',  addrect = 6, addCoef.col = 'white', number.cex = 0.7) 


coldata=as.factor(sampleMetaData[1:2])

library(pheatmap)


pheatmap(correlationMatrix,cutree_cols = 2)






